- platform: command_line
  switches:
    pihole_temp_disable:
      command_on: "curl -X GET 'http://192.168.0.13/admin/api.php?enable&auth='"
      command_off: "curl -X GET 'http://192.168.0.13/admin/api.php?disable=3600&auth='"
#        command_state: "curl -X GET 'http://192.168.10.11/admin/api.php?status'"
#        value_template: "{{ value_json.status == 'enabled' }}
